apiVersion: v1
kind: ConfigMap
metadata:
  name: lte-coming-soon
  labels:
    app: lte-coming-soon
data:
  NODE_ENV: production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lte-coming-soon
  labels:
    app: lte-coming-soon
spec:
  selector:
    matchLabels:
      app: lte-coming-soon
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: lte-coming-soon
        tier: frontend
    spec:
      containers:
      - name: lte-coming-soon
        image: docker.pkg.github.com/dubemarcantoine/location-tourisme-estrie-coming-soon/lte-coming-soon
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: lte-coming-soon
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: lte-coming-soon
  labels:
    app: lte-coming-soon
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: lte-coming-soon
