name: Production build
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@master
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@v1.4
      id: docker
      with:
        IMAGE_NAME: 'lte-coming-soon'
        DOCKERFILE_PATH: './Dockerfile'
        BUILD_CONTEXT: './'
      env:
        GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show location-tourisme-estrie > $GITHUB_WORKSPACE/.kubeconfig
    - name: Deploy to DigitalOcean Kubernetes
      uses: docker://lachlanevenson/k8s-kubectl
      with:
        args: --kubeconfig=/github/workspace/.kubeconfig rollout restart deployment/lte-coming-soon --namespace production
    - name: Verify deployment
      uses: docker://lachlanevenson/k8s-kubectl
      with:
        args: --kubeconfig=/github/workspace/.kubeconfig rollout status deployment/lte-coming-soon --namespace production
